### ISSUE TITLE
How to archive a tile provider?

### ISSUE THREAD

**Issue by veso266** [Gil-Epshtain/OSM-Tiles-Downloader#2]
Hi there, I want to archive all the tiles on an encient tile provider (since I am afraid that they will shut down their tile server and I have an app that I cannot change that is still using them)

the tile server is here: http://tiles.cdnst.net/base/

maps are organized in /z/x/y.png (I think)
and are using modestmaps-as3 (Modest Maps)
examples: http://tiles.cdnst.net/base/6/34/23.png

http://tiles.cdnst.net/base/6/34/24.png
http://tiles.cdnst.net/base/6/34/25.png
http://tiles.cdnst.net/base/6/34/26.png
http://tiles.cdnst.net/base/6/34/27.png
http://tiles.cdnst.net/base/6/34/28.png
http://tiles.cdnst.net/base/6/34/29.png
http://tiles.cdnst.net/base/6/34/30.png

http://tiles.cdnst.net/base/6/35/24.png
http://tiles.cdnst.net/base/7/35/24.png

so does someone know how can I download them all (including all zoom settings)?

if downloading is not an option, can I just render them and make them look like the above?

Thanks for Anwsering and Best Regards

**Comment by Gil-Epshtain** [comment]
Hi @veso266, sorry for taking me long time to answer, this is a low priority project which isn't supported any more.
I've fixed the build problems and update the framework to latest Angular version (v11.x). So now you can download and debug it.

I've added your map provider ( http://tiles.cdnst.net/base/ ) to the project and you can now select it (under the Download Server) and try to download tiles.

Unfortunately I could not make it work because this server is password protected. When I try to download tiles the server reject me request with 403 (forbidden) error. If you have a password you can now try and download relevant tiles.

**Comment by veso266** [comment]
Hi there, the server doesnt allow directory(it never asked me for a password and sadly I do not have it₩ listing but if you acsess to the file direcly: http://tiles.cdnst.net/base/6/34/28.png

It will show the picture

Since storing all the tiles would require a lot of space, I was wondering if its possible to render tiles on my own so they will look like the tiles on the map provider?

Thanks for anwsering and best regards

**Comment by Gil-Epshtain** [comment]
@veso266, I've made some additional research. You can use the "osm-tiles-downloader" to download tiles from your site - `tiles.cdnast`.

You will need to select the "Modest Maps" from the servers list.
Tring to download will fail, due to "CORS policy", you can overcome this problem by installing the Chrome extension [Allow CORS: Access-Control-Allow-Origin](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf).

Regarding your question, you have 2 choices getting Map tiles:
- Buy map tiles - there are a lot of different map tiles providers that provide tiles for different purposes (Traffic, Weather, Travel, etc...)
- Generate map tiles by yourself - You can use programs like QGIS or another equivalent to generating map data. Then you can convert the map data to Tile images.
